import './altium-parser/schematic-basics.mjs'
import './altium-parser/schematic-symbols.mjs'
import './altium-parser/schematic-layout.mjs'
import './altium-parser/schematic-regressions.mjs'
import './altium-parser/forge-relic.mjs'
