import assert from 'node:assert/strict'
import test from 'node:test'

import { PcbObjectOpacityPreviewScheduler } from '../../src/ui/PcbObjectOpacityPreviewScheduler.mjs'

class FakeLabel {
    textContent = ''
}

class FakeSliderContainer {
    label = new FakeLabel()

    /**
     * @param {string} selector
     * @returns {FakeLabel | null}
     */
    querySelector(selector) {
        if (selector === '.viewer-sidebar__object-opacity-value') {
            return this.label
        }
        return null
    }
}

class FakeInput {
    #container = new FakeSliderContainer()

    /**
     * @param {string} selector
     * @returns {FakeSliderContainer | null}
     */
    closest(selector) {
        if (selector === '.viewer-sidebar__object-slider') {
            return this.#container
        }
        return null
    }

    /**
     * @returns {string}
     */
    readLabel() {
        return this.#container.label.textContent
    }
}

class FakeStyle {
    attributes = new Map()
    textContent = ''

    /**
     * @param {string} name
     * @param {string} value
     * @returns {void}
     */
    setAttribute(name, value) {
        this.attributes.set(name, value)
    }
}

class FakeSvg {
    appended = []
    style = null

    ownerDocument = {
        createElementNS: () => new FakeStyle()
    }

    /**
     * @param {string} selector
     * @returns {FakeStyle | null}
     */
    querySelector(selector) {
        if (selector === 'style.pcb-object-opacity-preview-style') {
            return this.style
        }
        return null
    }

    /**
     * @param {FakeStyle} node
     * @returns {void}
     */
    appendChild(node) {
        this.style = node
        this.appended.push(node)
    }
}

class FakeWorker {
    listeners = new Map()
    messages = []

    /**
     * @param {string} type Event type.
     * @param {(event: { data: any }) => void} callback Event callback.
     * @returns {void}
     */
    addEventListener(type, callback) {
        this.listeners.set(type, callback)
    }

    /**
     * @param {any} message Worker message.
     * @returns {void}
     */
    postMessage(message) {
        this.messages.push(message)
    }

    /**
     * @param {any} data Worker response data.
     * @returns {void}
     */
    emitMessage(data) {
        this.listeners.get('message')?.({ data })
    }
}

class FakeDocument {
    svg = new FakeSvg()

    /**
     * @param {string} selector
     * @returns {FakeSvg | null}
     */
    querySelector(selector) {
        if (selector === '.pcb-view .pcb-svg') {
            return this.svg
        }
        return null
    }
}

/**
 * Verifies live opacity previews defer SVG style mutation off the input event.
 */
test('PcbObjectOpacityPreviewScheduler coalesces live opacity previews', () => {
    const callbacks = []
    const cssRequests = []
    const documentNode = new FakeDocument()
    const mount = { ownerDocument: documentNode }
    const input = new FakeInput()
    const scheduler = new PcbObjectOpacityPreviewScheduler({
        cssRenderer: (_hiddenKeys, opacities) => {
            cssRequests.push(opacities)
            return (
                '.pcb-svg .pcb-track { opacity: ' +
                opacities.tracks / 100 +
                '; }'
            )
        },
        frameScheduler: (callback) => {
            callbacks.push(callback)
            return callbacks.length
        }
    })

    scheduler.preview(mount, input, 'tracks', 45)
    scheduler.preview(mount, input, 'tracks', 20)

    assert.equal(input.readLabel(), '20%')
    assert.equal(cssRequests.length, 0)
    assert.equal(documentNode.svg.appended.length, 0)
    assert.equal(callbacks.length, 1)

    callbacks[0]()

    assert.deepEqual(cssRequests, [{ tracks: 20 }])
    assert.equal(documentNode.svg.appended.length, 1)
    assert.equal(
        documentNode.svg.style.textContent,
        '.pcb-svg .pcb-track { opacity: 0.2; }'
    )
})

/**
 * Verifies live opacity preview CSS can be generated by a worker.
 */
test('PcbObjectOpacityPreviewScheduler posts coalesced previews to a worker', () => {
    const callbacks = []
    const documentNode = new FakeDocument()
    const mount = { ownerDocument: documentNode }
    const input = new FakeInput()
    const worker = new FakeWorker()
    const scheduler = new PcbObjectOpacityPreviewScheduler({
        cssRenderer: () => {
            throw new Error('main-thread css should not be rendered')
        },
        frameScheduler: (callback) => {
            callbacks.push(callback)
            return callbacks.length
        },
        workerFactory: () => worker
    })

    scheduler.preview(mount, input, 'tracks', 35)
    scheduler.preview(mount, input, 'tracks', 15)
    callbacks[0]()

    assert.deepEqual(worker.messages, [
        {
            objectKey: 'tracks',
            opacity: 15,
            requestId: 1
        }
    ])
    assert.equal(documentNode.svg.appended.length, 0)

    worker.emitMessage({
        css: '.pcb-svg .pcb-track { opacity: 0.15; }',
        requestId: 1
    })

    assert.equal(documentNode.svg.appended.length, 1)
    assert.equal(
        documentNode.svg.style.textContent,
        '.pcb-svg .pcb-track { opacity: 0.15; }'
    )
})

/**
 * Verifies the fallback mode keeps live slider events cheap for heavy boards.
 */
test('PcbObjectOpacityPreviewScheduler supports commit-only fallback mode', () => {
    const documentNode = new FakeDocument()
    const input = new FakeInput()
    const scheduler = new PcbObjectOpacityPreviewScheduler({
        cssRenderer: () => {
            throw new Error('css should not be rendered')
        },
        frameScheduler: () => {
            throw new Error('frame should not be scheduled')
        },
        mode: PcbObjectOpacityPreviewScheduler.MODE_COMMIT_ONLY
    })

    scheduler.preview({ ownerDocument: documentNode }, input, 'tracks', 55)

    assert.equal(input.readLabel(), '55%')
    assert.equal(documentNode.svg.appended.length, 0)
})
